name: Test

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: pgsql, pdo_pgsql, gd, imagick, intl, xml, zip, pcntl

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Create .env file
      run: cp .env.github-ci .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Configure environment for testing
      run: |
        php artisan config:clear
        php artisan migrate --env=testing

    - name: Run Tests
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: test_db
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
      run: php artisan test


